# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/test/user/write/test_name
Accept: application/json

###

GET http://127.0.0.1:8000/test/user/read
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/read
Accept: application/json
