# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/User_read
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/User_write
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/Recipe_write
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/Recipe_read
Accept: application/json

###

