# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/user/read
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/user/write
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/recipe/write
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/recipe/read
Accept: application/json

###

GET  http://127.0.0.1:8000/test/async/search
Accept: application/json

###