POST http://localhost:8000/user/register
Content-Type: application/json

{
  "username": "{{$random.alphabetic(12)}}",
  "password": "test2234",
  "email": "{{$random.alphabetic(8)}}@gmail.com"
}
###
