name: Merge Bot

on:
  pull_request:
    types:
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: false
        reviewers: true
        checks_enabled: false
        method: squash
        delete_source_branch: false
